name: Publish assets

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish assets to S3
    runs-on: ubuntu-latest
    steps:
      - name: Set up rclone
        run: curl https://rclone.org/install.sh | sudo bash
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Publish assets to S3
        env:
          RCLONE_CONFIG_OWOCAFE_TYPE: s3
          RCLONE_CONFIG_OWOCAFE_PROVIDER: Minio
          RCLONE_CONFIG_OWOCAFE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          RCLONE_CONFIG_OWOCAFE_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          RCLONE_CONFIG_OWOCAFE_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
          RCLONE_CONFIG_OWOCAFE_NO_CHECK_BUCKET: "true"
          RCLONE_CONFIG_OWOCAFE_NO_HEAD: "true"
        run: rclone copy --no-check-dest assets/ "owocafe:${{ secrets.S3_BUCKET }}/assets/"
