name: Publish image

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Mastodon version
        id: version
        run: |
          echo "mastodon=$(sed -nr 's/^ARG MASTODON_VERSION="(.*)"$/\1/p' Dockerfile)" >> "$GITHUB_OUTPUT"
      - name: Generate tag
        id: tag
        run: |
          echo "bare=${{ steps.version.outputs.mastodon }}" >> "$GITHUB_OUTPUT"
          # A more semver-correct way of generating this would be to use "+" rather than "sha.".
          # Unfortunately, image tags cannot contain "+".
          echo "full=${{ steps.version.outputs.mastodon }}-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.bare }}
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.full }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
