name: Publish assets

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish assets to S3
    runs-on: ubuntu-latest
    steps:
      - name: Set up rclone
        run: curl https://rclone.org/install.sh | sudo bash
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Publish assets to S3
        env:
          RCLONE_CONFIG_OWOCAFE_TYPE: s3
          RCLONE_CONFIG_OWOCAFE_PROVIDER: Minio
          RCLONE_CONFIG_OWOCAFE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          RCLONE_CONFIG_OWOCAFE_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          RCLONE_CONFIG_OWOCAFE_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
        run: rclone copy assets/ "owocafe:${{ secrets.S3_BUCKET }}/assets/"
