name: Publish image

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  publish:
    name: Build and push image
    strategy:
      matrix:
        image:
          - dockerfile: Dockerfile
            name: ${{ github.repository }}
          - dockerfile: Dockerfile.streaming
            name: ${{ github.repository }}-streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Mastodon version
        id: version
        run: |
          echo "mastodon=$(sed -nr 's/^ARG MASTODON_VERSION="(.*)"$/\1/p' '${{ matrix.image.dockerfile }}')" >> "$GITHUB_OUTPUT"
      - name: Generate tag
        id: tag
        run: |
          echo "bare=${{ steps.version.outputs.mastodon }}" >> "$GITHUB_OUTPUT"
          # A more semver-correct way of generating this would be to use "+" rather than "sha.".
          # Unfortunately, image tags cannot contain "+".
          echo "full=${{ steps.version.outputs.mastodon }}-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.image.dockerfile }}
          tags: |
            ghcr.io/${{ matrix.image.name }}:${{ steps.tag.outputs.bare }}
            ghcr.io/${{ matrix.image.name }}:${{ steps.tag.outputs.full }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
