name: Build image

on:
  pull_request:

jobs:
  build:
    name: Build image
    strategy:
      matrix:
        image:
          - dockerfile: Dockerfile
            name: ${{ github.repository }}
          - dockerfile: Dockerfile.streaming
            name: ${{ github.repository }}-streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3
      - name: Build
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6
        with:
          file: ${{ matrix.image.dockerfile }}
          tags: |
            ${{ matrix.image.name }}:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
