name: Build image

on:
  pull_request:

jobs:
  build:
    name: Build image
    strategy:
      matrix:
        image:
          - dockerfile: Dockerfile
            name: ${{ github.repository }}
          - dockerfile: Dockerfile.streaming
            name: ${{ github.repository }}-streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - name: Build
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6
        with:
          file: ${{ matrix.image.dockerfile }}
          tags: |
            ${{ matrix.image.name }}:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
