name: Build image

on:
  pull_request:

jobs:
  build:
    name: Build image
    strategy:
      matrix:
        image:
          - dockerfile: Dockerfile
            name: ${{ github.repository }}
          - dockerfile: Dockerfile.streaming
            name: ${{ github.repository }}-streaming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3
      - name: Build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          file: ${{ matrix.image.dockerfile }}
          tags: |
            ${{ matrix.image.name }}:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
